### ISSUE TITLE
HeroCheatIntegration method broken

### ISSUE THREAD

**Issue by JavidPack** [Flashkirby/tMod-Settings-Configurator#1]
The method errors when cheatsheet is not enabled. You should not call a method with unresolvable method calls if the mod that has those methods is not enabled, as the weak references guide teaches.

Edit: Oh, I guess this mod is long abandoned, I'll let the person using this mod that ran into this error know, nevermind.

**Comment by Flashkirby** [comment]
Yeah sorry, this is very ancient and unless I can be convinced otherwise, not really necessary any more.
